#!/usr/bin/env python3
"""09 — Emit absolute raw.githubusercontent.com URL indexes for fetch-only agents.

Why this exists: a plain web-fetch agent (no shell, no GitHub MCP) cannot browse the
repo. GitHub blocks automated crawling of `/tree/` folder-listing pages via robots.txt,
and most fetch tools also refuse to open a URL they haven't already seen as text/link.
Relative links in the wiki (`[01-general.md](01-general.md)`) don't help — they don't
resolve to a fetchable URL. So navigation has to be "fetch this page and every next link
you need is already sitting in it as an absolute URL."

This script generates exactly that, from the files actually present:

    manuals/<slug>/wiki/all-files.md   one absolute raw URL per file in the manual
    MANUALS.md  (repo root)            entry points (absolute raw URLs) for every manual

Raw URLs use `raw.githubusercontent.com/<owner>/<repo>/<branch>/<path>` — plain text, not
the app-shell HTML of `/blob/` or `/tree/`, and untouched by the robots.txt block.

Usage:
    python scripts/09_link_index.py                     # all manuals + MANUALS.md
    python scripts/09_link_index.py manuals/<slug>/     # just that manual's all-files.md
    python scripts/09_link_index.py --repo owner/name --branch main   # override autodetect

Owner/repo/branch are auto-detected from `git remote get-url origin` and the default
branch; override with --repo / --branch (or env OIO_REPO / OIO_BRANCH) for forks/mirrors.
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _common import load_manifest  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW = "https://raw.githubusercontent.com/{repo}/{branch}/{path}"

# gitignored working intermediates — never linkable, never list them
SKIP_DIRS = {"pages", "raw-ocr"}
SKIP_FILES = {"prepared.pdf", "all-files.md"}


def detect_repo() -> str:
    if os.environ.get("OIO_REPO"):
        return os.environ["OIO_REPO"]
    try:
        url = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "remote", "get-url", "origin"],
            text=True).strip()
    except Exception:
        sys.exit("Could not detect the repo from git; pass --repo owner/name.")
    m = re.search(r"github\.com[:/]+([^/]+/[^/]+?)(?:\.git)?/?$", url)
    if not m:
        sys.exit(f"Unrecognized origin URL {url!r}; pass --repo owner/name.")
    return m.group(1)


def detect_branch() -> str:
    if os.environ.get("OIO_BRANCH"):
        return os.environ["OIO_BRANCH"]
    try:
        ref = subprocess.check_output(
            ["git", "-C", str(REPO_ROOT), "symbolic-ref", "--quiet",
             "refs/remotes/origin/HEAD"], text=True).strip()
        return ref.rsplit("/", 1)[-1] or "main"
    except Exception:
        return "main"


def raw_url(repo: str, branch: str, path: Path) -> str:
    rel = path.relative_to(REPO_ROOT).as_posix()
    return RAW.format(repo=repo, branch=branch, path=rel)


def manual_files(mdir: Path) -> list[Path]:
    """Every committed, fetchable file in a manual, in a useful reading order."""
    manifest = load_manifest(mdir)
    wiki = mdir / "wiki"
    ordered: list[Path] = []

    def add(p: Path):
        if p.is_file() and p.name not in SKIP_FILES and p not in ordered:
            ordered.append(p)

    # entry points first, then chapters/indexes, then source + data
    add(wiki / "llm-instructions.md")
    add(wiki / "00-index.md")
    add(mdir / "README.md")
    add(mdir / "manifest.yml")
    for f in sorted(wiki.glob("*.md")):
        add(f)
    src = manifest.get("source", {}).get("location")
    if src:
        add(mdir / src)
    data = mdir / "data"
    if data.is_dir():
        for f in sorted(data.rglob("*")):
            if f.is_file() and not any(part in SKIP_DIRS for part in f.parts):
                add(f)
    return ordered


def write_all_files(mdir: Path, repo: str, branch: str) -> int:
    files = manual_files(mdir)
    manifest = load_manifest(mdir)
    title = manifest.get("title", mdir.name)
    lines = [
        f"# {title} — every file (absolute URLs)", "",
        "_Machine-generated by `scripts/09_link_index.py` — do not hand-edit._", "",
        "Fetch-only navigation: this repo's folder pages (`/tree/…`) are blocked for "
        "automated crawling, so **use the raw URLs below**. Every file in this manual is "
        "listed here as an absolute `raw.githubusercontent.com` link — fetch any one "
        "directly; you never need to browse a folder.", "",
    ]
    for f in files:
        lines.append(f"- [{f.relative_to(mdir).as_posix()}]({raw_url(repo, branch, f)})")
    lines.append("")
    (mdir / "wiki" / "all-files.md").write_text("\n".join(lines), encoding="utf-8")
    return len(files)


def write_manuals_index(mdirs: list[Path], repo: str, branch: str) -> None:
    lines = [
        "# Manuals in this repo — entry points (absolute URLs)", "",
        "_Machine-generated by `scripts/09_link_index.py` — do not hand-edit._", "",
        "**Fetch-only / no shell / no GitHub MCP?** GitHub blocks automated browsing of "
        "`/tree/` folder pages, so you can't list a directory. Instead, start from a raw "
        "URL below and follow the links — every page here is plain-text-fetchable.", "",
    ]
    for mdir in mdirs:
        manifest = load_manifest(mdir)
        title = manifest.get("title", mdir.name)
        af = mdir / "wiki" / "all-files.md"
        idx = mdir / "wiki" / "00-index.md"
        li = mdir / "wiki" / "llm-instructions.md"
        lines += [
            f"## {title}", "",
            f"- **All files (every raw URL):** {raw_url(repo, branch, af)}",
            f"- Manual entry point: {raw_url(repo, branch, li)}",
            f"- Chapter index: {raw_url(repo, branch, idx)}", "",
        ]
    (REPO_ROOT / "MANUALS.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("manual_dir", nargs="?", help="one manual; omit for all + MANUALS.md")
    ap.add_argument("--repo", help="owner/name (default: autodetect from git remote)")
    ap.add_argument("--branch", help="branch (default: autodetect origin HEAD, else main)")
    args = ap.parse_args()

    repo = args.repo or detect_repo()
    branch = args.branch or detect_branch()

    if args.manual_dir:
        mdir = Path(args.manual_dir).resolve()
        if not (mdir / "manifest.yml").is_file():
            sys.exit(f"No manifest.yml in {mdir}")
        n = write_all_files(mdir, repo, branch)
        print(f"Wrote {mdir/'wiki'/'all-files.md'} ({n} files) for {repo}@{branch}")
        return 0

    # Manuals nest as manuals/<make>/<vehicle|engine>/<unit>/ — find them by manifest.
    manuals_root = REPO_ROOT / "manuals"
    mdirs = sorted({
        p.parent for p in manuals_root.glob("**/manifest.yml")
        if "_template" not in p.relative_to(manuals_root).parts
    })
    for mdir in mdirs:
        n = write_all_files(mdir, repo, branch)
        print(f"  {mdir.name}: {n} files")
    write_manuals_index(mdirs, repo, branch)
    print(f"Wrote MANUALS.md + {len(mdirs)} all-files.md for {repo}@{branch}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
